### ISSUE TITLE
Integrate logo into header

### ISSUE THREAD

**Issue by steelesh** [steelesh/UCollab#45]
- Add one of the logos defined by @alfardni to the project
- Should replace the "UCollab" text in header
- Consider different screen sizes, image size, correct format
- Changes should be in `navbar.tsx` component

**Comment by alfardni** [comment]
Integrated our UCollab logo into the navbar by replacing the "UCollab" text. The logo is responsive and adjusts well across different screen sizes. Verified in development to ensure it displays correctly on the site. This issue is now resolved and closed.
